import { Jost } from "next/font/google";
import "./globals.css";
import EaseOut from './components/template/EaseOutComponent';

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <EaseOut>
          {children}
        </EaseOut>
      </body>
    </html>
  );
}
